Rename accounts
chris-mazur/newbank_group9 pull request #15
Opened 2021-04-04 23:03 UTC by chris-mazur

Added new functionality:

RENAMEACC <CURRENT-NAME> <NEW-NAME> - rename your account

2021-04-05 10:55 UTC, AlexMxwl requested changes
This new functionality generally needs to be made more robust against user input errors. In doing so, I think there is a way to simplify its implementation.

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +				case "RENAMEACC":
I think "RENAMEACCOUNT" would be a more user-friendly command?

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +				"RENAMEACC <CURRENT-NAME> <NEW-NAME> - rename your account\n" +
Update this if you change the name of the command to "RENAMEACCOUNT".

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +		String renamed = requestParams[2];
Lines 137 and 138 will cause "Server error." if the customer does not enter the correct input parameters. 

Please implement a check so that this function can handle user error gracefully.

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +						tempAcc = new CheckingAccount(account);
This works, but I think that creating temporary accounts for the sake of having a single for loop in this function is making things more complicated than they need to be. In reality, each customer is unlikely to have a large number of bank accounts, so having multiple loops is not going to result in a significant performance penalty (and it would allow for easier creation of specific error/prompt messages for the user).

Surely all that this function needs to do is:
1. Confirm that the "current" account name exists
2. Confirm that the "renamed" account name does not already exist
3. Use the new Account.setName() method to make the change if the above conditions are satisifed

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/SavingsAccount.java
> +	}
If you decide to simplify the renameAccounts() method in NewBank, then this additional constructor will no longer be required.

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/CheckingAccount.java
> +	}
If you decide to simplify the renameAccounts() method in NewBank, then this additional constructor will no longer be required.

2021-04-05 10:55 UTC, AlexMxwl commented on newbank/server/Account.java
> +
If you decide to simplify the renameAccounts() method in NewBank, then this additional constructor will no longer be required.

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/NewBank.java
> +				case "RENAMEACC":
Changed

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/NewBank.java
> +				"RENAMEACC <CURRENT-NAME> <NEW-NAME> - rename your account\n" +
Changed

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/NewBank.java
> +		String renamed = requestParams[2];
I've introduced a new check in the new version.

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/NewBank.java
> +						tempAcc = new CheckingAccount(account);
That's true! I don't know what I was thinking! Now simplified.

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/SavingsAccount.java
> +	}
Removed.

2021-04-10 17:09 UTC, chris-mazur commented on newbank/server/CheckingAccount.java
> +	}
Removed

2021-04-10 17:10 UTC, chris-mazur commented on newbank/server/Account.java
> +
Removed

2021-04-11 18:48 UTC, merged