Admin deposit
chris-mazur/newbank_group9 pull request #17
Opened 2021-04-04 23:55 UTC by chris-mazur

Added admin only functionality:
(note that the Admin function is hard-coded)

"*********** ADMIN ONLY ***********\n" +
"DEPOSIT <AMOUNT> <CUSTOMER> <CUSTOMER'S ACCOUNT NAME> - Adds funds to one of your accounts; enter the command followed by the balance to be\n" +
"added, then the account name to deposit funds to.";

2021-04-05 11:17 UTC, AlexMxwl requested changes
I'm happy with this implementation - it just needs to be made more robust against invalid user inputs before being merged with the main branch.

2021-04-05 11:17 UTC, AlexMxwl commented on newbank/server/NewBank.java
>  	}
Happy for this method to be deleted completely rather than commented out.

2021-04-05 11:17 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +
This method will need some checks against invalid user inputs for AMOUNT, CUSTOMER and CUSTOMER'S ACCOUNT NAME. At the moment, the command line interface just returns "Server error."

Also, nice reuse of an existing method!

2021-04-05 11:34 UTC, chris-mazur commented on newbank/server/NewBank.java
> +
What did you do to get the Server Error? For me invalid inputs were handled by the previously implemented makePayment(customer,bankDetails)

2021-04-05 12:46 UTC, AlexMxwl commented on newbank/server/NewBank.java
> +
So I just logged in as Bhagy, and if I type in "DEPOSIT" without any other parameters it gives "Server error." The same happens if I give any incorrect number of parameters.

After the "Server error." occurs, any further attempts to use this command return nothing.

2021-04-10 12:16 UTC, chris-mazur commented on newbank/server/NewBank.java
> +
Hi Alex. I have just changed this. I've added a check if 4 arguments are provided in the DEPOSIT method and also fixed the Server Error caused by makePayment method. The issue was that even though the customer ID provided was wrong, it still wanted to retrieve a bank account name from that invalid user. It should be fine now.

2021-04-10 15:55 UTC, merged